

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - SQLSERVER_IP=35.224.74.201
      - SQLSERVER_DB=webappdb
      - SQLSERVER_USER=sqlserver
      - SQLSERVER_PASS=Annamma@1997
    depends_on:
      - frontend

